version: "3.3"
services:
  todo_service:
    build: todo_service
    volumes:
      - ./todo_service/:/src/
#    depends_on:
#      - redis
#      - localstack
#    env_file:
#      - .env

#  db:
#    image: postgres
#    volumes:
#      - postgres_data:/home/user/postgres/data
#    env_file:
#      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - todo_service