"""auto

Revision ID: 32ec9b36209d
Revises: 413caafd369f
Create Date: 2023-06-12 11:30:39.326469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ec9b36209d'
down_revision = '413caafd369f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
