"""auto

Revision ID: 413caafd369f
Revises: 555024daf8c7
Create Date: 2023-06-12 11:29:59.743301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413caafd369f'
down_revision = '555024daf8c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
