"""auto

Revision ID: 555024daf8c7
Revises: 30263c37ef55
Create Date: 2023-06-12 10:47:39.845604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555024daf8c7'
down_revision = '30263c37ef55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
