"""auto

Revision ID: 73c176ffcdc1
Revises: bb0d868dfaca
Create Date: 2023-05-30 12:22:16.717908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c176ffcdc1'
down_revision = 'bb0d868dfaca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
