"""auto

Revision ID: bb0d868dfaca
Revises: f4035b2b15a1
Create Date: 2023-05-30 12:02:08.459697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0d868dfaca'
down_revision = 'f4035b2b15a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
